apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bootstrap.yaml
- argocd-crd.yaml
- argocd-dex-server-config.yaml
- argocd-dex-server-deployment.yaml
- argocd-dex-server-service.yaml
- argocd-repo-server.yaml
- argocd-ingress.yaml
