apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-namespace.yaml
- 02-redis-deployment.yaml
- 03-redis-service.yaml
- 04-postgres-deployment.yaml
- 05-postgres-pvc.yaml
- 06-postgres-service.yaml
- 06-authentik-pvc.yaml
- 07-authentik-deployment.yaml
- 08-authentik-service.yaml
- 09-authentik-worker.yaml
